print ("Hello, human. I will be asking you some questions.")
name = input("What\'s your name?")
print(name, "? Your parents must hate you.")
age = input("How old are you?")
print("Aren\'t you a little too old to be pregnan- oh sorry, I didn\'t realize that you\'re, uh, \'big-boned\'.")
siblings = input("How many siblings do you have?")
print (siblings, "? Isn't that a lot?")
music = input("What kind of music do you prefer?")
print("Oh. Can't you do any better?")
future = input("What do you want to be when you grow up?")
print ("You want to be a(n)",future,"? Haha, I want a bag of popcorn and some Sprite when I see your hopes and dreams crushed!")
