print ("             __")
print ("            (__)")                   
print ("            lllll")   
print ("          iiiiiiii")   
print ("        lllllllllll")
print ("      iiiiiiiiiiiiiii")   
print ("    lllllllllllllllllll")   
print ("  iiiiiiiiiiiiiiiiiiiiiiii")
print ("llllllllllllllliiiiiiiiiiiii")  
print ("         |________|")
print ("         |________|")
print ("         |________|")
print ("         |________|")
print ("         |________|")

