print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                           IIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")
print ("IIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIII")    
